# modify this file so that it's 7 layers taking 40 by 40 pixel images
# 

!obj:pylearn2.train.Train {
    dataset: &train !obj:pylearn2_plankton.planktonDataConsolidated.PlanktonData {
        which_set: 'train',
        maxPixel: 40,
        rotate: True
    },
    model: !obj:pylearn2.models.mlp.MLP {
        batch_size: 100,
        input_space: !obj:pylearn2.space.Conv2DSpace {
            shape: [40, 40],
            num_channels: 1
        },
        layers: [ !obj:pylearn2.models.mlp.ConvRectifiedLinear {
                     layer_name: 'c0',
                     output_channels: 32,
                     irange: .05,
                     kernel_shape: [5, 5],
                     pool_shape: [1, 1],
                     pool_stride: [1, 1],
                     max_kernel_norm: 1.9365
                 }, !obj:pylearn2.models.mlp.ConvRectifiedLinear {
                     layer_name: 'c1',
                     output_channels: 32,
                     irange: .05,
                     kernel_shape: [5, 5],
                     pool_shape: [2, 2],
                     pool_stride: [2, 2],
                     max_kernel_norm: 1.9365
                 }
                 , !obj:pylearn2.models.mlp.ConvRectifiedLinear {
                     layer_name: 'c2',
                     output_channels: 48,
                     irange: .05,
                     kernel_shape: [5, 5],
                     pool_shape: [1, 1],
                     pool_stride: [1, 1],
                     max_kernel_norm: 1.9365
                 }
                 , !obj:pylearn2.models.mlp.ConvRectifiedLinear {
                     layer_name: 'c3',
                     output_channels: 48,
                     irange: .05,
                     kernel_shape: [5, 5],
                     pool_shape: [2, 2],
                     pool_stride: [2, 2],
                     max_kernel_norm: 1.9365
                 }
                 , !obj:pylearn2.models.mlp.ConvRectifiedLinear {
                     layer_name: 'c4',
                     output_channels: 64,
                     irange: .05,
                     kernel_shape: [3, 3],
                     pool_shape: [2, 2],
                     pool_stride: [2, 2],
                     max_kernel_norm: 1.9365
                 } 
                 , !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'f0',
                     dim: 121,
                     irange: .05,
                     max_col_norm: 1.9365,
                 }
                 , !obj:pylearn2.models.mlp.Softmax {
                     max_col_norm: 1.9365,
                     layer_name: 'y',
                     n_classes: 121,
                     istdev: .05
                 }
                 # add fully connected layer before Softmax? 
                 # Example: Sigmoid, RectifiedLinear, Maxout, tanh, Linear
                ],
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 100,
        learning_rate: .01,
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.Momentum {
            init_momentum: .5
        },
        monitoring_dataset:
            {
                'valid' : !obj:pylearn2_plankton.planktonDataConsolidated.PlanktonData  {
                              which_set: 'valid',
                              maxPixel: 40,
                              rotate: True
                          }
                , 'test'  : !obj:pylearn2_plankton.planktonDataConsolidated.PlanktonData  {
                              which_set: 'test',
                              maxPixel: 40,
                              rotate: True
                          }
            },
        cost: !obj:pylearn2.costs.cost.SumOfCosts { costs: [
            !obj:pylearn2.costs.cost.MethodCost {
                method: 'cost_from_X'
            }, !obj:pylearn2.costs.mlp.WeightDecay {
                coeffs: [ .00005, .00005, .00005, 0.0005, 0.0005, 0.005, 0.005] 
                #the length must agree with number of layers
            }
            ]
        },
        termination_criterion: !obj:pylearn2.termination_criteria.And {
            criteria: [
                !obj:pylearn2.termination_criteria.MonitorBased {
                    channel_name: 'valid_y_misclass',
                    prop_decrease: 0.01,
                    N: 100
                },
                !obj:pylearn2.termination_criteria.EpochCounter {
                    max_epochs: 300
                },
            ]
        },
    },
    extensions:
        [ !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: 'model_files/plankton_model2r.pkl'
        }, 
        !obj:pylearn2.training_algorithms.learning_rule.MomentumAdjustor {
            start: 1,
            saturate: 10,
            final_momentum: .99
        }
    ]
}

