!obj:pylearn2.train.Train {
    dataset: &train !obj:pylearn2_plankton.planktonDataPylearn2.PlanktonData {
        which_set: 'train',
        start: 0,
        stop: 20000
    },
    model: !obj:pylearn2.models.mlp.MLP {
        batch_size: 100,
        input_space: !obj:pylearn2.space.Conv2DSpace {
            shape: [28, 28],
            num_channels: 1
        },
        layers: [ !obj:pylearn2.models.maxout.MaxoutConvC01B {
                     layer_name: 'c0',
                     num_pieces: 1,
                     num_channels: 32,
                     irange: .05,
                     kernel_shape: [5, 5],
                     pool_shape: [2, 2],
                     pool_stride: [2, 2],
                     max_kernel_norm: 1.9365
                 }, !obj:pylearn2.models.maxout.MaxoutConvC01B {
                     layer_name: 'c1',
                     num_pieces: 1,
                     num_channels: 48,
                     irange: .05,
                     kernel_shape: [5, 5],
                     pool_shape: [2, 2],
                     pool_stride: [2, 2],
                     max_kernel_norm: 1.9365
                 }
                 , !obj:pylearn2.models.maxout.MaxoutConvC01B {
                     layer_name: 'c2',
                     num_pieces: 1,
                     num_channels: 64,
                     irange: .05,
                     kernel_shape: [3, 3],
                     pool_shape: [2, 2],
                     pool_stride: [2, 2],
                     max_kernel_norm: 1.9365
                 }
                 , !obj:pylearn2.models.maxout.Maxout {
                     layer_name: 'f0',
                     num_units: 250,
                     irange: .05,
                     max_col_norm: 1.9365,
                 }
                 , !obj:pylearn2.models.mlp.Softmax {
                     max_col_norm: 1.9365,
                     layer_name: 'y',
                     n_classes: 121,
                     istdev: .05
                 }
                 # add fully connected layer before Softmax? 
                 # Example: Sigmoid, RectifiedLinear, Maxout, tanh, Linear
                ],
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 100,
        learning_rate: .05,
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.Momentum {
            init_momentum: .5
        },
        monitoring_dataset:
            {
                'valid' : !obj:pylearn2_plankton.planktonDataPylearn2.PlanktonData {
                              which_set: 'train',
                              start: 25000,
                              stop:  30300
                          }
            },
        cost: !obj:pylearn2.costs.mlp.dropout.Dropout {
            input_include_probs: { 'c0' : .8 },
            input_scales: { 'c0': 1. }
        },
        termination_criterion: !obj:pylearn2.termination_criteria.And {
            criteria: [
                !obj:pylearn2.termination_criteria.MonitorBased {
                    channel_name: "valid_y_misclass",
                    prop_decrease: 0.01,
                    N: 100
                },
                update_callbacks: !obj:pylearn2.training_algorithms.sgd.ExponentialDecay {
                    decay_factor: 1.00004,
                    min_lr: .000001
                },
                #!obj:pylearn2.termination_criteria.EpochCounter {
                #    max_epochs: 200
                #}
            ]
        },
    },
    extensions:
        [ !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "model_files/plankton_conv_visualize2_model.pkl"
        }, 
        !obj:pylearn2.training_algorithms.learning_rule.MomentumAdjustor {
            start: 1,
            saturate: 20,
            final_momentum: .99
        },
        !obj:pylearn2.training_algorithms.sgd.LinearDecayOverEpoch {
            start: 1,
            saturate: 500,
            decay_factor: .01
        }
    ]
}


